import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Global registry for all systems in the build
const systemsData = {};

/**
 * MyST Plugin for Dynamical Systems Simulator with PyScript
 *
 * Usage in markdown:
 * ```{dynsim}
 * :params: [{"id": "tau", "label": "τ", "min": 0.1, "max": 2, "step": 0.1, "value": 1}]
 * :plotType: timeseries
 * :plotConfig: {"title": "My System", "xaxis": {"title": "Time", "range": [0, 50]}}
 * :initialState: {"v": 0, "t": 0}
 * :initialX: 0
 * :height: 400
 *
 * from typing import NamedTuple
 * import numpy as np
 *
 * class State(NamedTuple):
 *     v: float  # membrane potential
 *     t: float  # time
 *
 * def step(x, state, p):
 *     # x: current input/output (feedback)
 *     # state: State namedtuple with internal variables
 *     # p: parameters as SimpleNamespace
 *
 *     dv = (-state.v + x + p.current) / p.tau
 *     v_new = state.v + 0.02 * dv
 *     x_new = np.tanh(p.weight * v_new)
 *
 *     return (x_new, State(v=v_new, t=state.t + 0.02))
 * ```
 */

const plugin = {
  name: 'Dynamical Systems Simulator',
  directives: [
    {
      name: 'dynsim',
      doc: 'Embed an interactive dynamical systems simulator with Python',
      body: {
        type: 'string',  // Raw Python code
        required: true
      },
      options: {
        params: {
          type: String,
          doc: 'JSON array of parameter definitions [{id, label, min, max, step, value}, ...]'
        },
        plotType: {
          type: String,
          doc: 'Plot type: 2d, 3d, or timeseries (default: timeseries)'
        },
        plotConfig: {
          type: String,
          doc: 'JSON object for Plotly configuration'
        },
        initialState: {
          type: String,
          doc: 'JSON object for initial state (default: {"t": 0})'
        },
        initialX: {
          type: Number,
          doc: 'Initial input/output value (default: 0)'
        },
        height: {
          type: Number,
          doc: 'Height in pixels (default: 400)'
        },
        dt: {
          type: Number,
          doc: 'Timestep for integration (default: 0.02)'
        }
      },
      run(data) {
        console.log('[Plugin] dynsim directive run() called');
        console.log('[Plugin] data.body:', data.body);
        console.log('[Plugin] data.options:', data.options);

        const pythonCode = data.body || '';
        const id = `dynsim-${Math.random().toString(36).substr(2, 9)}`;

        console.log('[Plugin] Generated ID:', id);
        console.log('[Plugin] Python code length:', pythonCode.length);

        // Build config object
        const config = {
          params: data.options?.params || '[]',
          plotType: data.options?.plotType || 'timeseries',
          plotConfig: data.options?.plotConfig || '{}',
          initialState: data.options?.initialState || '{"t": 0}',
          initialX: data.options?.initialX ?? 0,
          height: data.options?.height || 400,
          dt: data.options?.dt || 0.02
        };

        // Store system data in registry
        systemsData[id] = {
          pythonCode: pythonCode,
          config: config
        };

        // Write data file to _static/js/ (prefix with 0- to load before dynamical_systems.js)
        const outputPath = join(__dirname, '..', '_static', 'js', '0-dynsim-systems.js');
        const jsContent = `// Auto-generated by dynamical-systems plugin
window.dynSimSystemsData = ${JSON.stringify(systemsData, null, 2)};
console.log('[DynSim Plugin] Loaded', Object.keys(window.dynSimSystemsData).length, 'system definitions');
`;

        try {
          mkdirSync(dirname(outputPath), { recursive: true });
          writeFileSync(outputPath, jsContent, 'utf8');
          console.log('[Plugin] Wrote systems data file:', outputPath);
        } catch (e) {
          console.error('[Plugin] Failed to write systems data file:', e);
        }

        console.log('[Plugin] Registered system:', id);
        console.log('[Plugin] Total systems:', Object.keys(systemsData).length);

        // Return container div with loading spinner
        return [
          {
            type: 'html',
            value: `<div id="${id}" class="dynsim-python-container" style="min-height: ${config.height}px;"><div class="visualization-loading"></div></div>`
          }
        ];
      }
    }
  ]
};

export default plugin;
